# Generated by Django 2.0.7 on 2019-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190530_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('sweets', 'sweets'), ('beverages', 'beverages'), ('appetizers', 'appetizers'), ('entres', 'entres')], max_length=60),
        ),
    ]
