# Generated by Django 2.0.7 on 2019-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190530_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('beverages', 'beverages'), ('sweets', 'sweets'), ('entres', 'entres'), ('appetizers', 'appetizers')], max_length=60),
        ),
    ]
