# Generated by Django 2.0.7 on 2019-05-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190530_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('beverages', 'beverages'), ('appetizers', 'appetizers'), ('sweets', 'sweets'), ('entres', 'entres')], max_length=60),
        ),
    ]
