# Generated by Django 2.0.7 on 2019-05-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190530_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('entres', 'entres'), ('beverages', 'beverages'), ('sweets', 'sweets'), ('appetizers', 'appetizers')], max_length=60),
        ),
    ]
