# Generated by Django 2.0.7 on 2019-05-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190530_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('sweets', 'sweets'), ('appetizers', 'appetizers'), ('entrees', 'entrees'), ('beverages', 'beverages')], max_length=60),
        ),
    ]
