# Generated by Django 2.0.7 on 2019-05-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20190530_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('beverages', 'beverages'), ('appetizers', 'appetizers'), ('sweets', 'sweets'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
