# Generated by Django 2.0.7 on 2019-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20190530_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('sweets', 'sweets'), ('appetizers', 'appetizers'), ('beverages', 'beverages'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
