# Generated by Django 2.0.7 on 2019-05-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190531_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('entrees', 'entrees'), ('beverages', 'beverages'), ('appetizers', 'appetizers'), ('sweets', 'sweets')], max_length=60),
        ),
    ]
