# Generated by Django 2.0.7 on 2019-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20190531_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('beverages', 'beverages'), ('entrees', 'entrees'), ('sweets', 'sweets'), ('appetizers', 'appetizers')], max_length=60),
        ),
    ]
